name=input("what is your name")
branch=input("what is your branch")
gender=input("what is your gender")
collegename=input("what is the name of your college")
age=input("what is your age")
print(" name:",name)
print("Branch:",branch)
print("Gender:",gender)
print("Collegename:",collegename)
print("Age:",age)
